### ISSUE TITLE
Function update api

### ISSUE THREAD

**Issue by chin8** [scc-digitalhub/digitalhub-core#49]
calling the update API with metadata "name" changed, the server return the old value.

Example changing metadata from "sd" to "name"

Request URL:
`http://localhost:8080/api/v1/-/prj1/functions/sd/01177744-1231-48b6-8958-c6d6aa061060
`
Request Method: PUT
`{"id":"01177744-1231-48b6-8958-c6d6aa061060","kind":"dbt","metadata":{"labels":[],"project":"prj1","created":"2024-01-10T08:19:20.657+00:00","updated":"2024-01-10T09:35:52.698+00:00","name":"name","version":"01177744-1231-48b6-8958-c6d6aa061060","description":"descrizione","embedded":false},"name":"sd","project":"prj1","spec":{"source":"we"},"status":{"state":"CREATED"}}`

server response:
```
{
    "id": "01177744-1231-48b6-8958-c6d6aa061060",
    "kind": "dbt",
    "metadata": {
        "project": "prj1",
        "labels": [],
        "created": "2024-01-10T08:19:20.657+00:00",
        "updated": "2024-01-10T09:35:52.698+00:00",
        "name": "sd",
        "version": "01177744-1231-48b6-8958-c6d6aa061060",
        "description": "descrizione",
        "embedded": false
    },
    "name": "sd",
    "project": "prj1",
    "spec": {
        "source": "we"
    },
    "status": {
        "state": "CREATED"
    }
}
```

**Comment by trubbio** [comment]
Now the name,version and embedded field in Metadata are update correctly
