### ISSUE TITLE
Wrong behaviour API Last version

### ISSUE THREAD

**Issue by chin8** [scc-digitalhub/digitalhub-core#50]
Calling API for the last versions of a group of object like functions, I get all the versions, even the old ones.

Example:
http://localhost:8080/api/v1/-/prj1/functions?page=0&size=50&sort=id%2CASC

What I expect to get is a list with 2 elements named funct1 and funct 2.
What I get is a list that in my opinion includes all versions.
{
    “content”: [
        {
            “id”: “1bd69980-906d-4f7f-be5f-4675e08384f5”,
            “kind”: “dbt”,
            “metadata”: {
                “project”: “prj1",
                “labels”: [
                    “lab 0"
                ],
                “created”: “2024-01-10T15:21:58.124+00:00",
                “updated”: “2024-01-10T15:21:58.124+00:00",
                “name”: “funct1",
                “version”: “1bd69980-906d-4f7f-be5f-4675e08384f5",
                “description”: “descrizione”,
                “embedded”: false
            },
            “name”: “funct1”,
            “project”: “prj1”,
            “spec”: {
                “source”: “dbt1"
            },
            “status”: {
                “state”: “CREATED”
            }
        },
        {
            “id”: “2de05c83-4831-46a7-8929-9264e6889185”,
            “kind”: “nefertem”,
            “metadata”: {
                “project”: “prj1",
                “labels”: [],
                “created”: “2024-01-10T15:22:45.559+00:00”,
                “updated”: “2024-01-10T15:22:45.559+00:00”,
                “name”: “funct2”,
                “version”: “2de05c83-4831-46a7-8929-9264e6889185”,
                “description”: “descr”,
                “embedded”: false
            },
            “name”: “funct2",
            “project”: “prj1",
            “spec”: {},
            “status”: {
                “state”: “CREATED”
            }
        },
        {
            “id”: “85263dd8-cc4f-41c1-a552-109d2a7681ed”,
            “kind”: “nefertem”,
            “metadata”: {
                “project”: “prj1”,
                “created”: “2024-01-10T15:22:34.484+00:00”,
                “updated”: “2024-01-10T15:22:34.484+00:00”,
                “name”: “funct2”,
                “version”: “85263dd8-cc4f-41c1-a552-109d2a7681ed”,
                “embedded”: false
            },
            “name”: “funct2",
            “project”: “prj1",
            “spec”: {},
            “status”: {
                “state”: “CREATED”
            }
        },
        {
            “id”: “9bd1b750-8855-4537-96fa-fd15dd61de0a”,
            “kind”: “dbt”,
            “metadata”: {
                “project”: “prj1”,
                “labels”: [
                    “lab 0”
                ],
                “created”: “2024-01-10T15:21:18.513+00:00”,
                “updated”: “2024-01-10T15:21:42.058+00:00”,
                “name”: “funct1”,
                “version”: “9bd1b750-8855-4537-96fa-fd15dd61de0a”,
                “description”: “descr”,
                “embedded”: false
            },
            “name”: “funct1",
            “project”: “prj1",
            “spec”: {
                “source”: “dbt1”
            },
            “status”: {
                “state”: “CREATED”
            }
        }
    ],
    “pageable”: {
        “pageNumber”: 0,
        “pageSize”: 50,
        “sort”: {
            “unsorted”: false,
            “sorted”: true,
            “empty”: false
        },
        “offset”: 0,
        “paged”: true,
        “unpaged”: false
    },
    “totalPages”: 1,
    “totalElements”: 4,
    “last”: true,
    “numberOfElements”: 4,
    “first”: true,
    “size”: 50,
    “number”: 0,
    “sort”: {
        “unsorted”: false,
        “sorted”: true,
        “empty”: false
    },
    “empty”: false
}

**Comment by trubbio** [comment]
Fixed for all models that use Context.
